language: php

php: 
 - 5.4
 - 5.5
 - 5.6
 - 7.0
 - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
 - vendor/bin/phpspec run
 - vendor/bin/phpmd src text codesize,unusedcode,naming
 - vendor/bin/phpcs --standard=psr2 src
